M48
; DRILL file {KiCad 8.0.2} date 2024-07-19T10:45:16+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-19T10:45:16+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0512
%
G90
G05
T1
X3.3214Y-2.6281
X3.3214Y-2.9431
T2
X7.659Y-5.2
T3
X3.2464Y-4.077
X3.4826Y-4.077
T4
X7.3657Y-5.2
M30
