M48
; DRILL file {KiCad 8.0.1} date 2024-07-11T11:53:26+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-11T11:53:26+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
%
G90
G05
T1
X7.9842Y-5.7254
X8.2118Y-5.7254
T2
X2.1416Y-3.839
X2.4172Y-3.839
M30
